// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKo8a73KQolvWCtBMIZB72rHwlssQIl0',
    appId: '1:1007775136606:web:79e1a2eb04df882447edcf',
    messagingSenderId: '1007775136606',
    projectId: 'liscan3d',
    authDomain: 'liscan3d.firebaseapp.com',
    storageBucket: 'liscan3d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDof20BWU0FcgjY4TCfEEBfpaWyvZIVW_k',
    appId: '1:1007775136606:ios:60447819c177d43347edcf',
    messagingSenderId: '1007775136606',
    projectId: 'liscan3d',
    storageBucket: 'liscan3d.firebasestorage.app',
    iosClientId: '1007775136606-lfr2db6o3k9roipmhv4ppaa3kibm9uu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lidarApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQKo8a73KQolvWCtBMIZB72rHwlssQIl0',
    appId: '1:1007775136606:web:3e5b347ae2392c3b47edcf',
    messagingSenderId: '1007775136606',
    projectId: 'liscan3d',
    authDomain: 'liscan3d.firebaseapp.com',
    storageBucket: 'liscan3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDof20BWU0FcgjY4TCfEEBfpaWyvZIVW_k',
    appId: '1:1007775136606:ios:60447819c177d43347edcf',
    messagingSenderId: '1007775136606',
    projectId: 'liscan3d',
    storageBucket: 'liscan3d.firebasestorage.app',
    iosClientId: '1007775136606-lfr2db6o3k9roipmhv4ppaa3kibm9uu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lidarApplication',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjP9gVTpQ2ziZ7FJo-4zAsJ2yNzFeBrM',
    appId: '1:1007775136606:android:cf29b4640ff1befc47edcf',
    messagingSenderId: '1007775136606',
    projectId: 'liscan3d',
    storageBucket: 'liscan3d.firebasestorage.app',
  );

}